AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates the Lambda function and API for the PyTorch inference application.

Parameters: 
  BucketName: 
    Type: String
    Default: somebucket
    Description: Enter the name of the S3 bucket storing your PyTorch model artefacts.
  ObjectKey: 
    Type: String
    Default: somekey
    Description: Enter the S3 object key path of your PyTorch model artefacts.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
    Function:
        Timeout: 30
        MemorySize: 1750

Resources:

  PyTorchFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Architectures:
          - x86_64
        Environment:
          Variables:
            MODEL_BUCKET: !Ref BucketName
            MODEL_KEY: !Ref ObjectKey
        Role: arn:aws:iam::363437592425:role/SAM_ML_LAMBDA_S3
        Events:
            PyTorch:
                Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                Properties:
                    Path: /invocations
                    Method: post
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./app
        DockerTag: python3.9-v1
                        
Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    PyTorchApi:
      Description: "API Gateway endpoint URL for Prod stage for PyTorch function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invocations/"

    PyTorchFunction:
      Description: "PyTorch Lambda Function ARN"
      Value: !GetAtt PyTorchFunction.Arn                       